Add controllers
GirichevVasiliy/java-shareit pull request #1
Opened 2023-02-09 18:38 UTC by GirichevVasiliy

2023-02-10 16:11 UTC, boristm1 requested changes

2023-02-10 16:11 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +            throw new RequestError(HttpStatus.NOT_FOUND, "Вещь с ID " + itemId + " не найдена");
а вместо этого можно просто вернуть false (updateItem может просто возвращать true, если обновил, и false, если не найден - зачем возвращать item?), либо сделать для этого NotFoundException

2023-02-10 16:11 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +    public Item addItem(Item item, User user) {
зачем возвращать тот же item, который мы передали?

2023-02-10 16:11 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +                if (item.getName() == null) {
не очень понял, зачем эти проверки? На валидность item будет проверен на уровне контроллеров и сервисов, т. е. в репозиторий попадет уже валидный item

2023-02-11 11:39 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long id;
Выполнено.

2023-02-11 11:42 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank(message = "Поле \"Название\" должно быть заполнено")
Выполнено.

2023-02-11 11:43 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/enams/StatusBooking.java
> +package ru.practicum.shareit.enams;
Выполнено.

2023-02-11 11:44 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/error/RequestError.java
> +public class RequestError extends ResponseStatusException {
Выполнено.

2023-02-11 11:48 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    //Добавление новой вещи и юзер кто добавил, владелец
Выполнено.

2023-02-11 13:54 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +            throw new RequestError(HttpStatus.NOT_FOUND, "Вещь с ID " + itemId + " не найдена");
В тестах постмана идет проверка обновления вещи.

2023-02-11 13:57 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +    public Item addItem(Item item, User user) {
Возвращаю из памяти тот, что мы сохранили return items.get(idItem) + тут же назначается id, ну и так требуют тесты постмана для проверки.

2023-02-11 14:03 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +                if (item.getName() == null) {
Эти проверки для того чтобы обновить конкретное поле, так как в постмане прилетает дто очень интересно: "null, null, почта...." или "null, имя, null...." и таких вариаций куча, я не стал писать для каждого случая, если дто прилетел только с почтой или именем для обновления, то я беру старые поля для тех, что в новом дто == null, а то что не null обновляю.

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/booking/enam/StatusBooking.java
> +package ru.practicum.shareit.booking.enam;
надо было положить рядом с классом Booking в тот же пакет, т. к. это его статусы

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/exception/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
похоже, нигде не выбрасывается - можно удалить

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/exception/exceptions/ResourceNotFoundException.java
> +@ResponseStatus(code = HttpStatus.NOT_FOUND)
лучше все соответствия исключений Http-кодам держать в одном месте - в ErrorHandler (тем более там уже задан код для этого исключения) - тут можно удалить

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Data
вместо Data тут лучше использовать Value, тогда код будет чище:

```
@Value
public class ItemDto {
    Long id;
    @NotBlank(message = "Поле \"Название\" должно быть заполнено")
    String name;
    @NotBlank(message = "Поле \"Описание\" должно быть заполнено")
    String description;
    @BooleanFlag
    @NotNull
    Boolean available; // статус о том, доступна или нет вещь для аренды;
    Long requestId; // если вещь была создана по запросу другого пользователя, то в этом поле будет храниться ссылка на соответствующий запрос.
    User owner;
}
```

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +        return items.get(idItem);
можно просто вернуть item - мы же его только что сохранили

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> itemsRepository = itemRepository.getItemsByUser(userId);
получать вообще все вещи не рационально, если нам надо обновить всего одну, а в случае с базой это вообще будет слишком затратно - есть вещь или нет проще узнать через getItemById, а проверив хозяина этой вещи можно определить, принадлежит она юзеру или нет

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/dto/MapperItem.java
> +public class MapperItem {
лучше назвать ItemMapper (Item - тут прилагательное)

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/dto/MapperUser.java
> +public class MapperUser {
лучше назвать UserMapper

2023-02-12 18:54 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        List<User> allUsers = userRepository.getAllUsers();
то же самое, что и в ItemService

2023-02-12 18:57 UTC, boristm1 approved these changes

2023-02-19 09:26 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/booking/enam/StatusBooking.java
> +package ru.practicum.shareit.booking.enam;
Выполнено.

2023-02-19 09:26 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/exception/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
Выполнено.

2023-02-19 09:50 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +        return items.get(idItem);
Выполнено.

2023-02-19 10:02 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/user/dto/MapperUser.java
> +public class MapperUser {
Исправлено

2023-02-19 10:02 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/dto/MapperItem.java
> +public class MapperItem {
Исправлено.

2023-02-19 10:07 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        List<User> allUsers = userRepository.getAllUsers();
В постмане есть проверка, что ты не можешь обновить почту и задать ее как у другого пользователя. Придется проверять список пользователей на не совпадение почты.

2023-02-19 10:08 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Data
Учту при дальнейшей разработке, пока не понятно нужен юзер в дто или нет.

2023-02-19 10:11 UTC, GirichevVasiliy commented on src/main/java/ru/practicum/shareit/exception/exceptions/ResourceNotFoundException.java
> +@ResponseStatus(code = HttpStatus.NOT_FOUND)
Учту. После обращения к  ментору, есть момент, что убрав статус @ResponseStatus(code = HttpStatus.NOT_FOUND) в этом классе, почему то не выбрасывается статус в постман.

2023-02-19 10:45 UTC, merged